In [1]:
import pandas as pd

In [2]:
import numpy as np 
import matplotlib.pyplot as plt
import yfinance as yf

In [3]:
spy = yf.download(
    tickers = "SPY",
    start = "2005-01-01",
    end = "2025-01-01",
    multi_level_index = False
)

[*********************100%***********************]  1 of 1 completed

In [4]:
spy.head()

                Close       High        Low       Open    Volume
Date
2005-01-03  80.973518  81.956239  80.704279  81.821616  55748000
2005-01-04  79.984100  81.135095  79.721593  81.081246  69167600
2005-01-05  79.432121  80.266760  79.425389  79.923479  65667300
2005-01-06  79.836014  80.199487  79.600431  79.721589  47814700
2005-01-07  79.721542  80.253289  79.512879  80.078283  55847700

In [5]:
spy.tail()

                 Close        High         Low        Open    Volume
Date
2024-12-24  589.714722  589.753989  583.997032  584.575691  33160100
2024-12-26  589.753906  590.871896  586.556708  587.949332  41219100
2024-12-27  583.545898  586.262548  579.377784  586.027122  64969300
2024-12-30  576.886719  580.338918  573.150129  576.563120  56578800
2024-12-31  574.788025  579.260165  573.159975  578.544189  57052700

In [6]:
spy.to_csv("data/spy.csv")