In [1]:
import pandas as pd

In [2]:
import numpy as np 
import matplotlib.pyplot as plt
import yfinance as yf

In [20]:
spy = yf.download(
    tickers = "SPY",
    start = "2005-01-01",
    end = "2025-01-01",
    multi_level_index = False
)

[*********************100%***********************]  1 of 1 completed

In [21]:
spy.head()

                Close       High        Low       Open    Volume
Date
2005-01-03  80.973511  81.956231  80.704271  81.821609  55748000
2005-01-04  79.984093  81.135088  79.721585  81.081239  69167600
2005-01-05  79.432144  80.266783  79.425412  79.923502  65667300
2005-01-06  79.835991  80.199464  79.600408  79.721566  47814700
2005-01-07  79.721558  80.253305  79.512894  80.078298  55847700

In [22]:
spy.tail()

                 Close        High         Low        Open    Volume
Date
2024-12-24  589.714661  589.753928  583.996971  584.575630  33160100
2024-12-26  589.753967  590.871957  586.556768  587.949392  41219100
2024-12-27  583.545837  586.262486  579.377723  586.027060  64969300
2024-12-30  576.886719  580.338918  573.150129  576.563120  56578800
2024-12-31  574.787964  579.260104  573.159914  578.544128  57052700

In [23]:
spy.to_csv("data/spy.csv")